#!/usr/bin/env python3
"""Refresh compact AI navigation files for this repository.

The script intentionally writes summaries and file lists only. It never embeds
source file contents into the generated context files.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

CONTEXT_FILES = [
    "AGENTS.md",
    "CLAUDE.md",
    "ARCHITECTURE.md",
    "PROJECT_MAP.md",
    "TASK_LOG.md",
    ".repo-files.txt",
]

IGNORED_DIRS = {
    ".git",
    ".next",
    ".claude",
    ".venv",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "node_modules",
    "out",
    "output",
    "test-results",
    "tmp",
    "venv",
}

IGNORED_SUFFIXES = {
    ".db",
    ".log",
    ".pem",
    ".pyc",
    ".tsbuildinfo",
}

IGNORED_FILENAMES = {
    ".DS_Store",
    ".env",
    ".env.local",
    ".repo-files.txt",
    "package-lock.json",
}


DOC_SECTIONS = {
    "AGENTS.md": (
        "## AI Context Automation",
        """- Before starting work, read `PROJECT_MAP.md`, `ARCHITECTURE.md`, `TASK_LOG.md`, and `.repo-files.txt` to get oriented.
- Avoid whole-repository scans unless the focused context files are insufficient.
- Use the smallest relevant file set for the task, then expand only when the code points you there.
- Run `npm run ai:context` after structural or functionality changes that affect the project map, architecture notes, task log, or file inventory.
- Update `PROJECT_MAP.md` when files, routes, modules, or ownership boundaries change.
- Update `TASK_LOG.md` when user-visible functionality, workflow decisions, or important implementation notes change.""",
    ),
    "CLAUDE.md": (
        "## AI Context Automation",
        """Before work, read `PROJECT_MAP.md`, `ARCHITECTURE.md`, `TASK_LOG.md`, and `.repo-files.txt`.

Avoid broad repository scans unless those files do not contain enough context. Prefer the smallest relevant file set, and update `PROJECT_MAP.md` plus `TASK_LOG.md` when structure or functionality changes.""",
    ),
}


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def should_skip_dir(path: Path) -> bool:
    return path.name in IGNORED_DIRS


def should_skip_file(path: Path) -> bool:
    if path.name in IGNORED_FILENAMES:
        return True
    if path.name.startswith(".env."):
        return True
    return path.suffix in IGNORED_SUFFIXES


def iter_repo_files() -> list[Path]:
    files: list[Path] = []

    def walk(directory: Path) -> None:
      for child in sorted(directory.iterdir(), key=lambda item: item.name.lower()):
          if child.is_dir():
              if not should_skip_dir(child):
                  walk(child)
              continue
          if child.is_file() and not should_skip_file(child):
              files.append(child)

    walk(ROOT)
    return files


def group_files(paths: list[Path]) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = {}
    for path in paths:
        rel = relative(path)
        top = rel.split("/", 1)[0]
        if "/" not in rel:
            top = "."
        groups.setdefault(top, []).append(rel)
    return dict(sorted(groups.items()))


def render_repo_files(paths: list[Path]) -> str:
    groups = group_files(paths)
    lines = [
        "# Repository File Inventory",
        "",
        "Generated by: `python3 scripts/update-ai-context.py`",
        "",
        "Purpose: compact AI navigation. This file lists repository paths only; it does not include source code.",
        "",
        "Ignored directories: "
        + ", ".join(sorted(IGNORED_DIRS)),
        "",
        f"Tracked inventory count: {len(paths)} files",
        "",
        "## Context Files",
        "",
    ]

    for context_file in CONTEXT_FILES:
        if (ROOT / context_file).exists():
            lines.append(f"- {context_file}")

    lines.extend(["", "## Files By Area", ""])

    for group, entries in groups.items():
        label = "root" if group == "." else group
        lines.extend([f"### {label}", ""])
        for entry in entries:
            lines.append(f"- {entry}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def append_section_if_missing(path: Path, heading: str, body: str) -> bool:
    if not path.exists():
        return False

    text = path.read_text(encoding="utf-8")
    if heading in text:
        return False

    updated = text.rstrip() + f"\n\n{heading}\n\n{body.strip()}\n"
    path.write_text(updated, encoding="utf-8")
    return True


def ensure_task_log() -> bool:
    path = ROOT / "TASK_LOG.md"
    if path.exists():
        return False

    path.write_text(
        """# Task Log

Compact running notes for important project work. Keep this newest-first, focused on decisions and behavior changes rather than command transcripts.

## Recent Changes

- 2026-04-28: Added project-level AI context automation scaffolding.

## Notes For Future Agents

- Update this file when structure, workflow, deployment behavior, or user-visible functionality changes.
- Keep entries short and link to the relevant files or PRs when useful.
""",
        encoding="utf-8",
    )
    return True


def main() -> None:
    changed: list[str] = []

    if ensure_task_log():
        changed.append("TASK_LOG.md")

    for filename, (heading, body) in DOC_SECTIONS.items():
        if append_section_if_missing(ROOT / filename, heading, body):
            changed.append(filename)

    repo_files = iter_repo_files()
    output_path = ROOT / ".repo-files.txt"
    rendered = render_repo_files(repo_files)
    if not output_path.exists() or output_path.read_text(encoding="utf-8") != rendered:
        output_path.write_text(rendered, encoding="utf-8")
        changed.append(".repo-files.txt")

    if changed:
        print("Updated AI context files:")
        for filename in changed:
            print(f"- {filename}")
    else:
        print("AI context files are already up to date.")


if __name__ == "__main__":
    main()
